---
title: "Sentiment Classification of Kenya COVID-19 Vaccine Tweets"
author: "by andrewmolo"
output:
    tufte::tufte_html: default
    code_folding: hide
---

```{r}
```
# Introduction 
Sentiment analysis, also known as opinion mining is a process of analysing digital text with an aim of classifying the tone of a message.[^1] The main aim of sentiment analysis is to identify opinions and attitudes towards a particular topic or entity. Prior to this analysis, 3 main sentiments _(positive, negative and neutral)_ are derived from the text by use of machine learning models. 

Also, the digital text in context can be further classified into different emotions the text elucidates.[^2] This is done by use of lexicons which are present across systems and languages used in developing machine learning models. 
<!-- [[1]](https://aws.amazon.com/what-is/sentiment-analysis/). During the COVID-19 pandemic,  -->

This dashboard synthesises COVID-19 vaccine tweets generated from Twitter by Kenyans on Twitter *(["#KOT"](https://twitter.com/search?q=%23KOT&src=typeahead_click))* using sentiment analysis.


# Context of research
This is part of my project in Msc. Computer Science from The University of Nairobi. The aim of the research is to understand the different perceptions and opinions of Kenyans on Twitter, popularly known as _#KOT_ [^3] have about the discourse on rollout, implementation, potential side-effects and general conversation revolving around COVID-19 vaccines as well as the immunisation program implemented by Kenya's Minsitry of Health (MoH) together with the relevant health stakeholders.

# Data
The dataset was extracted from twitter using Twitter v2 API at different temporal intervals between 2021 and late 2022. The total number of observations were 1135 and 15 columns.  


# Exploratory Data Analysis
The sentiment analysis results section has two parts: Filter section and data visualisation section. On the filter section one has to either select negative or positive sentiment using the drop down or/and implement a time range using the date range function. The three charts and one table will dynamically change according to the filter(s) applied. Data visualisation catalogue supporting sentiment analysis include:

* **Sentiment scores over time** - A line chart that shows the sentiment scores across the duration of when the tweets were posted. Each tweet has a time stamp of when it was posted on twitter. 
Sentiment scores are values assigned to single words depending on the emotional tone the word elucidates.[[2]](https://www.tidytextmining.com/sentiment.html) These values are present in the NRC Word Emotional lexicon [[3]](http://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm).
* **Sentiment scores per location** - A bar graph showing the sentiment scores of location based on geo-tagged tweets only. Data cleaning had to be performed on this column due to irrelevant locations. Caveat: Not all tweets present in this analysis were geo-tagged. 
* **Sentiment scores per emotions** - The NRC Word Emotional lexicon classifies words into different emotions depending on the tone of the text. The degree each emotion elucidates is represented by a value which can either be positive or negative. The higher the value, the higher the weight of the emotion in the text. Hence this graph plots the emotions present in the words with their corresponding values. From a glimpse, the highest negative emotion among  vis-à-vis their values. 
* **Tweets table** - This is a table containing the tweets, emotional tone the tweets elucidates and the date when the tweets were posted. The beauty of this section is that one can download the tweets as either PDF or excel depending on the filters applied.

## LSTM model summary
LSTM stands for Long short-term memory. Its a machine learning model used to predict either a dichotomous response variable or a trichotomous response variable based on textual data as inputs. LSTM is part of a larger family of neural networks called recurrent neural networks (RNN). 

LSTM model implemented in this project is Bidirectional, meaning that this model consist of two LSTMs: one taking the input in a forward direction, and the other in a backwards direction. BiLSTMs effectively increase the amount of information available to the network, improving the context available to the algorithm (e.g. knowing what words immediately follow and precede a word in a sentence). [[4]](https://paperswithcode.com/method/bilstm)

Bidirectional model summary is represented by Cross-entropy plot also known as negative log likelihood 

[^1]: https://aws.amazon.com/what-is/sentiment-analysis/
[^2]: https://www.sciencedirect.com/topics/computer-science/sentiment-analysis
[^3]: https://twitter.com/search?q=%23KOT





<!-- two plots. Cross-entropy and Accuracy plot. Interpretation of these plots is detailed in that section.  -->
